# Generated by Django 4.1 on 2022-08-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='due_date',
        ),
        migrations.AddField(
            model_name='dividend',
            name='due_day',
            field=models.CharField(default='01', max_length=2),
            preserve_default=False,
        ),
    ]
