# Generated by Django 4.1 on 2022-08-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0002_remove_dividend_due_date_dividend_due_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='div_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='div_id',
            field=models.ManyToManyField(to='sales_manager.dividend'),
        ),
    ]
