# Generated by Django 4.1 on 2022-08-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0004_dividend_is_active_dividend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='div_id',
            field=models.ManyToManyField(related_name='div', to='sales_manager.dividend'),
        ),
    ]
