# Generated by Django 4.1 on 2022-08-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0007_remove_sale_dividens_sale_div_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='div_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_manager.dividend'),
        ),
    ]
