# Generated by Django 4.1 on 2022-08-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0009_sale_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='status',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('payment_date', models.DateField(default=None)),
                ('billing_month', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Atrasado', 'Atrasado'), ('Em dias', 'Em dias'), ('A vencer', 'A vencer')], default='Em dias', max_length=20)),
                ('sales', models.ManyToManyField(to='sales_manager.sale')),
            ],
        ),
    ]
