# Generated by Django 4.1 on 2022-08-15 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0012_invoice_invoice_date_alter_invoice_billing_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_month',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 15, 0, 31, 52, 19576)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 0, 31, 52, 19531)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
