# Generated by Django 4.1 on 2022-08-15 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0013_alter_invoice_billing_month_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Movement',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_month',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 15, 1, 22, 8, 136393)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 25, 1, 22, 8, 136350)),
        ),
    ]
