# Generated by Django 4.1 on 2022-08-27 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0014_rename_sale_movement_alter_invoice_billing_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dividend',
            name='email',
            field=models.EmailField(default=None, max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dividend',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dividend',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='password',
            field=models.CharField(default='123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='dividend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_manager.dividend'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_month',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 27, 18, 19, 3, 676878)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 18, 19, 3, 676833)),
        ),
    ]
