# Generated by Django 4.1 on 2022-08-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0015_dividend_date_of_birth_dividend_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_month',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 27, 18, 20, 37, 770510)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 18, 20, 37, 770467)),
        ),
    ]
