# Generated by Django 4.1 on 2022-08-27 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0016_alter_invoice_billing_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_month',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 27)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 6, 18, 21, 48, 360968)),
        ),
    ]
