# Generated by Django 4.1 on 2022-09-04 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0017_alter_invoice_billing_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='dividend',
            name='due_day',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_month',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 4)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 14, 21, 13, 36, 799205)),
        ),
    ]
